In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve,roc_auc_score,classification_report,precision_score


In [3]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
df['Species'] = df['Species'].replace({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})


In [6]:
x = df.drop(['Id','Species'],axis = 1)
y = df['Species']

In [7]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=1,stratify=y)

In [8]:
y_test.value_counts()

2    15
0    15
1    15
Name: Species, dtype: int64

In [9]:
clf_model = LogisticRegression(multi_class='ovr') # One Vs Rest
clf_model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [10]:
y_pred = clf_model.predict(x_test)
y_pred

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 2, 2, 1, 0,
       0], dtype=int64)

In [13]:
y_pred_prob = clf_model.predict_proba(x_test)
y_pred_prob


0                 1               2
[3.61965026e-05, 3.41589378e-01, 6.58374426e-01],  >> CLass 2
[7.87974999e-01, 2.12022695e-01, 2.30633454e-06],  >> class 0
[3.26510816e-01, 6.71338722e-01, 2.15046192e-03],  >>  class 1
[8.50466721e-01, 1.49529750e-01, 3.52954463e-06]   >> Class 0



0.3 0.7   >> class 1
0.4 0.6   >> class 1
0.9 0.1   >> class 0
0.8 0.2   >> class 0

SyntaxError: invalid syntax (<ipython-input-13-d0d697ab86d4>, line 5)

In [14]:
test_accuracy = accuracy_score(y_test,y_pred)
print("Accuracy on Testing Dataset is: ",test_accuracy)

Accuracy on Testing Dataset is:  0.9333333333333333


In [15]:
y_pred_train = clf_model.predict(x_train)
train_accuracy = accuracy_score(y_train,y_pred_train)
print("Accuracy on Testing Dataset is: ",train_accuracy)

Accuracy on Testing Dataset is:  0.9523809523809523


In [16]:
multilabel_confusion_matrix(y_test,y_pred)

array([[[30,  0],
        [ 0, 15]],

       [[29,  1],
        [ 2, 13]],

       [[28,  2],
        [ 1, 14]]], dtype=int64)

In [17]:
[28,  2],
[ 1, 14]]

           Pred 0     Pred 1
Actual 0   TN         FP            (30)
Actual 1   FN         TP            (15)

SyntaxError: unmatched ']' (<ipython-input-17-16e5b004edcb>, line 2)

In [18]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0, 13,  2],
       [ 0,  1, 14]], dtype=int64)

In [19]:
clf_report = classification_report(y_test,y_pred)
print("Classification Report \n",clf_report)

Classification Report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.93      0.87      0.90        15
           2       0.88      0.93      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



In [20]:
shivajinagar  0
katraj   1 
warje  2
.
.
wakad  199

20
23
24
.
.
60

high  2
medium  1
low 0


SyntaxError: invalid syntax (<ipython-input-20-76ffc28dee31>, line 1)

In [22]:
# x_test

In [26]:
clf_model.predict(x_test)

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 2, 2, 1, 0,
       0], dtype=int64)

In [27]:
x_test.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
148            6.2           3.4            5.4           2.3
5              5.4           3.9            1.7           0.4
6              4.6           3.4            1.4           0.3
106            4.9           2.5            4.5           1.7
75             6.6           3.0            4.4           1.4

In [28]:
clf_model.predict(x_test.head())

array([2, 0, 0, 1, 1], dtype=int64)

In [30]:
clf_model.predict(x_test.iloc[1:2])

array([0], dtype=int64)

In [44]:
x_test.iloc[1:2]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
5            5.4           3.9            1.7           0.4

In [45]:
# y_test

148    2
5      0
6      0
106    2
75     1
71     1
108    2
68     1
111    2
16     0
15     0
127    2
8      0
57     1
47     0
76     1
141    2
66     1
74     1
147    2
102    2
12     0
65     1
121    2
94     1
56     1
98     1
144    2
43     0
113    2
11     0
0      0
62     1
53     1
107    2
112    2
37     0
25     0
1      0
50     1
120    2
149    2
54     1
7      0
9      0
Name: Species, dtype: int64

In [32]:
x_test.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')

In [38]:
def predict_class(SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm):
    
    prediction = clf_model.predict([[SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm]])
    print("Predicted class is :",prediction[0])
    return prediction[0]

In [39]:
predict_class(5,2,3,4)

Predicted class is : 2


2

In [43]:
import pickle
import os
model_folder_path = 'model'
if not os.path.exists(model_folder_path):
    os.mkdir(model_folder_path)
    
pickle.dump(clf_model,open(f'{model_folder_path}/model.pkl','wb'))

In [49]:
import pickle
import os
model_folder_path = 'model'

model = [clf_model,clf_model]
pickle.dump(clf_model,open(f'{model_folder_path}/model.pkl','wb'))

In [48]:
import json
column_names = list(x_test.columns)

column = {"column_names":column_names}

with open('column.json','w') as f:
    f.write(json.dumps(column))